### ISSUE TITLE
可以说明一下编译所用的工具和步骤等等吗？

### ISSUE THREAD

**Issue by orz12** [huajiqaq/Hydrogen#1]

**Comment by huajiqaq** [comment]
androlua

**Comment by 1human** [comment]
哎呦！今天突然还刷新了下版本号15.0

**Comment by huajiqaq** [comment]
> _No description provided._

**Comment by orz12** [comment]
> androlua

但这个版本可多了， FusionApp reOpenLua+ AndroLuaGQ AndroLua+ 想咨询下具体用的是哪个呀

**Comment by huajiqaq** [comment]
理论每一个版本都可以 当然预览时可能会报错 因为本软件使用了androidx一部分内容 推荐一些支持androidx 比如aidelua eddielua等 否则你需打包将dex压缩进软件再签名才可 dex是项目的classess2.dex文件

**Comment by 1human** [comment]
巨佬，麻烦升级target api，不要在根目录下创建文件夹了！
