### ISSUE TITLE
设置每次打开页面失效

### ISSUE THREAD

**Issue by amokiel** [huajiqaq/Hydrogen#10]
重新安装了刚才更新的版本，权限都给了，也登录了，点击设置每次打开页面没有反应。其它选项好像都正常，另外可否将页面固定折叠的布局
![Screenshot_20230729_191316_com zhihu hydrogen](https://github.com/huajiqaq/Hydrogen/assets/70591216/09e97a0c-7862-41ba-83ac-936d6b2eff48)
可以一直保持折叠状态，要不然上面空白有点多，影响显示区域，显示区域大一些更好。开发者辛苦了，多谢！

**Comment by huajiqaq** [comment]
恢复了
