### ISSUE TITLE
“查看对话列表”视图下无法打开图片

### ISSUE THREAD

**Issue by Diaojinping** [huajiqaq/Hydrogen#101]
![Screenshot_20240829_130103_com.zhihu.hydrogen.x_edit_2467939298792163.jpg](https://github.com/user-attachments/assets/59e4016e-2f23-4295-9792-8f0d37e44e05)

![Screenshot_20240829_130036_com.zhihu.hydrogen.x.jpg](https://github.com/user-attachments/assets/6f365f79-19e1-4f75-aca9-51d7a9a05332)

**Comment by Diaojinping** [comment]
同样是关于评论区的问题也附在这里：无法单独回复某个人的评论

**Comment by huajiqaq** [comment]
这里测试可以回复 可能知乎评论有审核

**Comment by Diaojinping** [comment]
> 这里测试可以回复 可能知乎评论有审核

ok，我试了一下其他的也可以回复。但是那个查看图片的问题可以解决吗？
