### ISSUE TITLE
升级最新版（0.541）后，原有保存到本地的内容无法查看

### ISSUE THREAD

**Issue by fenhaizi** [huajiqaq/Hydrogen#103]
只能在“左上角三杠-->本地”看到标题，但是点进去后一片空白。

升级后新保存的内容能正常查看。

**Comment by huajiqaq** [comment]
请重新保存并手动删除文件 先有逻辑已改为直接转换为html

**Comment by huajiqaq** [comment]
安卓10以上路径在/sdcard/android/data/com.zhihu.hydrogen.x/目录下 请手动删除mht文件
