### ISSUE TITLE
在某人的用户页面查看ta的回答，无法按赞数排序

### ISSUE THREAD

**Issue by fenhaizi** [huajiqaq/Hydrogen#104]
点击按赞数排序后立刻（几乎无延迟）出现各种exception，最终也没能按赞数排序。

（点开“按时间排序/按赞数排序”下拉菜单后，即便点击“按时间排序”依然exception,只不过由于默认按时间排序，因此这个做法无意义）

**Comment by huajiqaq** [comment]
稍后重新下载最新版修复
