### ISSUE TITLE
版本0.544查看某个回答的详情页会报错

### ISSUE THREAD

**Issue by icoding168** [huajiqaq/Hydrogen#105]
![Screenshot_20240901_170425](https://github.com/user-attachments/assets/9b37da42-cfff-4659-8b75-ff66c7cc4bd2)
【回答】【如何看待经典曲目《云宫迅音》随游戏新作《黑神话：悟空》火遍全球？】西游记作曲许镜清: https://www.zhihu.com/question/665540185/answer/3612178407

**Comment by huajiqaq** [comment]
会在下一版本解决该问题
