### ISSUE TITLE
隐藏热榜的热度显示

### ISSUE THREAD

**Issue by amokiel** [huajiqaq/Hydrogen#11]
经过观察后发现，热榜的热度值没有显示的必要。只有前几个热度上百万，后面都显示6万热度。并且已经有热度排行榜数字排序了。这样热度显示没什么意义了，不如专注于提问本身。请求可以隐藏热榜的热度显示。
开发者辛苦了，由衷表达感谢！

**Comment by huajiqaq** [comment]
非常感谢你的支持和反馈，我很高兴你喜欢我的app。我已经修复了你提出的问题，希望你能在下一个版本中体验到。关于热榜的热度显示，我认为这是一个有趣的功能，可以让用户了解不同话题的关注度。不过，如果你觉得这个功能没有必要，或者影响了你的阅读体验，你可以选择隐藏它。你只需要在设置中找到热榜选项，然后关闭热度显示即可。另外，我想给你分享一个小技巧，如果你想更方便查看热榜内容，你也可以直接访问https://www.zhihu.com/billboard。这是一个可选的方式，只是为了让你有更多的选择和便利。再次感谢你对我的app的关注和建议，如果你有任何其他问题或意见，请随时告诉我。
