### ISSUE TITLE
可否禁用在退出回答后自动刷新

### ISSUE THREAD

**Issue by Diaojinping** [huajiqaq/Hydrogen#112]
在主页看到一个感兴趣的问题点开回答后，再返回主页会自动刷新，导致主页推荐内容与之前不一样，能否设置一个选项禁用退出后的自动刷新？

**Comment by huajiqaq** [comment]
这里并未做相对于的自动刷新的设置 是不是触发了设备的内存回收功能了呢？

**Comment by Diaojinping** [comment]
试了一下，开启全屏模式后退出回答不会自动刷新，只是显示一次刷新的🔄的图标，就很奇怪

**Comment by huajiqaq** [comment]
你的安卓版本是安卓14吗？

**Comment by huajiqaq** [comment]
如果已经给予了存储权限 你可以手动上传/sdcard/androlua/crash的日志文件

**Comment by Diaojinping** [comment]
已解决，手机后台崩溃导致
