### ISSUE TITLE
点赞和未点赞 颜色可否明显区分

### ISSUE THREAD

**Issue by puzzle9** [huajiqaq/Hydrogen#118]
现在这两个色很接近 不好确定

**Comment by huajiqaq** [comment]
这里觉得没有问题 想不到用什么颜色做对比

**Comment by puzzle9** [comment]
![已赞](https://github.com/user-attachments/assets/b434c01e-f8ac-4190-b14f-123b31e7700d)
![未赞](https://github.com/user-attachments/assets/d8ed3911-07a6-4f64-99f8-12e7862a00a8)

这个只有数字进行了变色
可否在图标上进行改动 以 `Filled` 和 `Outlined` 类型进行区别
