### ISSUE TITLE
Wish to be able to specify the saved local files' save path

### ISSUE THREAD

**Issue by JasonJarvan** [huajiqaq/Hydrogen#12]
你好，各位亲爱的开发者们
❤
我正在使用安卓10+的版本，我希望

- 可以设置保存到本地的目录位置，这是最好的；
- 或者退而求其次，设置导出文件的保存位置；
- 如果不行，希望可以将导出文件的默认保存位置放入一个新的文件夹,例如emulated/storage/0/Hydrogen/Hydrogen.zip ，而非直接保存到emulated/storage/0/Hydrogen.zip.

💘
原因是我使用syncthing进行手机-电脑的文件同步，然而emulated/storage/0这个文件夹是不允许同步的。如果可以放入其下的文件夹，那么就可以同步了。
💕
我也想贡献代码，但是我的主要语言是Java+TS+C#, 对于Lua实在力有未逮。
如果可以有机会通过我的好友请求（新版反馈是添加一个QQ好友，我加了），我将不胜荣幸。
谢谢，致一线的开发者们！🍻

**Comment by huajiqaq** [comment]
最新版已经可以自定义目录了
