### ISSUE TITLE
进入热榜界面就会报错，可无限次触发

### ISSUE THREAD

**Issue by abcdesteve** [huajiqaq/Hydrogen#125]
0.549版本，已登录
com.luajava.LuaException: Runtime error: /data/user/0/com.zhihu.hydrogen.x/files/home.lua:1230: attempt to index a nil value (global 'networkInfo')
stack traceback:
	/data/user/0/com.zhihu.hydrogen.x/files/home.lua:1230: in function 'onStart'

**Comment by huajiqaq** [comment]
是会一直触发吗？理论上onstart回调在一次只会触发一次

**Comment by abcdesteve** [comment]
> 是会一直触发吗？理论上onstart回调在一次只会触发一次

每一次返回首页都会
