### ISSUE TITLE
移动网络下不显示图片能不能不要一直提示呢？

### ISSUE THREAD

**Issue by a1029602653** [huajiqaq/Hydrogen#129]
这个一直提示确实有点烦，希望大佬可以改一下

**Comment by huajiqaq** [comment]
不开启智能无图就没事 即使开启了 手动点击关闭 就可以下次不提示

**Comment by a1029602653** [comment]
没有开智能无图呀

**Comment by huajiqaq** [comment]
软件由于考虑到并不是太多人需要更新 所以不手动检测更新是不会接受到最新版本的 你可以在关于查看是否为最新版
