### ISSUE TITLE
占用运行内存

### ISSUE THREAD

**Issue by XHJXHJXHJXHJ** [huajiqaq/Hydrogen#135]
打开系统文件app时侧滑栏显示hydrogen的数据，在此期间，**hydrogen会自启**，占用运行内存，不符合小而美规则
![Screenshot_20241130_094401](https://github.com/user-attachments/assets/8d89b534-e987-4dda-86af-617d3f2562a1)

**Comment by huajiqaq** [comment]
然而这是系统文件自带特性 因为在较高版本中无法访问data目录 **软件共享了部分provide以便共享data目录** 系统文件夹app显示时必须要启动软件

**Comment by huajiqaq** [comment]
当长期不使用 系统文件夹app应该会默认关闭app 并没有打开软件实际activity 只不过打开了 application下的 provider而已
