### ISSUE TITLE
应用更新至最新版后报错  ＂onScroll＂

### ISSUE THREAD

**Issue by 321yida** [huajiqaq/Hydrogen#15]
![Screenshot_20231106_141723](https://github.com/huajiqaq/Hydrogen/assets/67246596/6dd5e86f-15d3-4684-b27a-f5887050f851)
在主页的所有页面均有上述错误

**Comment by gudianxingkongmeng** [comment]
有同样的问题

**Comment by Canco-Wan** [comment]
同样
onScrolI
com.luajava.Lua Exception: Runtime error. /data/user/0/ com.zhihu.hydrogen.x/files/ home.lua:482: attempt to index a nil value (field
stack traceback:
/data/user/0/
com.zhihu.hydrogen.x/files/ home.lua:482: in function </data/ user/0/com.zhihu.hydrogen.x/
files/home.lua:473>
