### ISSUE TITLE
App的主页部分很多页面已404了

### ISSUE THREAD

**Issue by ONE223** [huajiqaq/Hydrogen#18]
设备：pixel5 A14
问题：账号登录的情况下，主页(关闭了其他按钮)很多页面甚至有段时间全部页面都显示404无法访问，但是官方客户端内同一个问题却可以看得到内容，
不知道是不是官方屏蔽了网页端的入口，希望可以修复下。
软件版本：官方最新版本

**Comment by ONE223** [comment]
![Screenshot_20231124-155125](https://github.com/huajiqaq/Hydrogen/assets/68263164/a479847d-5af9-4c8a-9751-90a6d9f0cf73)

**Comment by ONE223** [comment]
有qq联系吗？github要求录屏文件限于10mb，你这边原生自带的录屏8秒就占用了26mb

**Comment by huajiqaq** [comment]
> 有qq联系吗？github要求录屏文件限于10mb，你这边原生自带的录屏8秒就占用了26mb

点击软件内反馈按钮即可联系我

**Comment by huajiqaq** [comment]
也可以通过腾讯问卷上传文件 反馈在软件右上角 反馈 如果短期内没有反馈 我就更新了最新版了

**Comment by huajiqaq** [comment]
一般来说 不会出现这个bug 因为即使触碰到风控也会有验证或提示 而不是直接返回404

**Comment by ONE223** [comment]
看来是设置里在浏览器内查看这个选项不能打开，一打开主页的内容就404，其他页面都是正常的。2023年12月3日 10:28，CNE ***@***.***>写道：今天早上突然就正常了，不知道为什么(不知道是不是设置里在浏览器内查看需要关闭)之前在酷安问过酷友也有出现类似的问题。2023年12月3日 09:50，ddpp ***@***.***>写道：
一般来说 不会出现这个bug 因为即使触碰到风控也会有验证或提示 而不是直接返回404
