### ISSUE TITLE
刷新老是重复的内容

### ISSUE THREAD

**Issue by W4J1e** [huajiqaq/Hydrogen#23]
版本：0.41
描述：每次打开应用，刷几条后就会发现以前读到过的内容，手动下拉刷新后，仍然会出现这样的问题。
不光是问题一样，答案也是之前刷过的。
请求开发者有时间关注一下。

**Comment by W4J1e** [comment]
#13

**Comment by huajiqaq** [comment]
不知道怎么解决

**Comment by W4J1e** [comment]
@huajiqaq 好嘞，辛苦了哟。
