### ISSUE TITLE
夜间模式加载内容闪屏问题

### ISSUE THREAD

**Issue by zxk2099** [huajiqaq/Hydrogen#25]
夜间模式加载内容时, 内容部分是先黑屏, 再白屏, 再加载文字内容, 再切换深色, 造成闪屏问题, 希望可以优化一下 : )

**Comment by huajiqaq** [comment]
哪个页面啊 是回答页还是其他页

**Comment by zxk2099** [comment]
@huajiqaq 回答页

**Comment by huajiqaq** [comment]
可以给一个示例视频吗 现在不明白怎么优化 在我这里无法复现
