### ISSUE TITLE
更新0.42后打开回答和想法会报错

### ISSUE THREAD

**Issue by 20171213** [huajiqaq/Hydrogen#26]
![Screenshot_20240206-115010_crDroid Home.png](https://github.com/huajiqaq/Hydrogen/assets/34502902/8472d4a7-84f4-4f67-a27c-8eb8dcc3c48a)

![Screenshot_20240206-114949_Hydrogen.png](https://github.com/huajiqaq/Hydrogen/assets/34502902/2693ad03-baea-49a7-915d-c55c7fb948d4)

**Comment by huajiqaq** [comment]
无法复现

**Comment by huajiqaq** [comment]
已尝试修复
