### ISSUE TITLE
更新0.5后依然无法联网 提示runtime error

### ISSUE THREAD

**Issue by Aplx4689** [huajiqaq/Hydrogen#33]
![Screenshot_2024-04-03-05-01-07-38_1004997cf52b64ddd9ef91b00a21abf9](https://github.com/huajiqaq/Hydrogen/assets/165845333/7d924b9b-97a7-4543-a3e0-7ae1e7e36fe9)

**Comment by huajiqaq** [comment]
在设置中打开允许执行代码 点你右上角 执行以下代码
function safeCall(func, ...)
  -- 使用pcall包裹要调用的函数及其参数
  local success, resultOrError = pcall(func, ...) -- ... 表示可变数量的参数
  -- 检查是否成功执行
  if success then
    -- 没有发生错误，直接返回函数的正常结果
    return resultOrError
   else
    local tipdia=AlertDialog.Builder(this)
    .setTitle("提示(长按可复制)")
    .setMessage(resultOrError)
    .setPositiveButton("我知道了", nil)
    .setCancelable(false)
    .show()
    tipdia.findViewById(android.R.id.message).TextIsSelectable=true
    return nil, resultOrError
  end
end

function safecall_function(func)
  return function(...)
    -- 调用原函数并返回结果
    return safeCall(func, ...) -- 注意将self作为第一个参数传递给原方法
  end
end

function safecall_class(myTable)
  -- 遍历表，为函数创建代理
  for k, v in pairs(myTable) do
    if type(v) == "function" then
      -- 创建代理函数
      local proxyFunc = safecall_function(v)
      -- 替换表中的原函数为代理函数
      myTable[k] = proxyFunc
    end
  end
end

safecall_class(zHttp)
随后再次报错将会有弹窗显示 将弹窗内容中的文字发给我

**Comment by Aplx4689** [comment]
联网已恢复 提交一个bug,设置内更改字号提示弹窗自动弹出无法关闭
![Screenshot_2024-04-03-22-16-58-22_1004997cf52b64ddd9ef91b00a21abf9](https://github.com/huajiqaq/Hydrogen/assets/165845333/1506621c-bb66-4748-bf98-b11fecd43f6f)
