### ISSUE TITLE
知乎网页端调起该客户端的问题

### ISSUE THREAD

**Issue by ProgramDog404** [huajiqaq/Hydrogen#35]
# 35
## 这不是个客户端本身的问题
官方最近更新了网页端调起应用的网页，导致现在无法在网页端直接调起该客户端。官方端尚未测试，但添加了模块的官方端经测试亦无法调起。希望作者及时跟进，实在无法实现相关功能，或许可以添加一个输入框。用户将网页端对应页面复制网页链接后，粘贴至客户端直接打开对应页面

**Comment by huajiqaq** [comment]
在下版本发布
