### ISSUE TITLE
对“问题”增加赞数排序

### ISSUE THREAD

**Issue by Silverwolf-x** [huajiqaq/Hydrogen#45]
现在“问题”栏目下有如下功能：
- 分享
- 按时间排序
- 按默认排序
- 问答
能否增加“按点赞数排序”和“收藏数排序”，使得永和能看到更加高质量的回答，谢谢！

**Comment by huajiqaq** [comment]
等有时间会添加上的

**Comment by huajiqaq** [comment]
知乎并没有提供相关排序api 所以无法添加
