### ISSUE TITLE
用wifi时大部分功能不能联网，wifi有网络

### ISSUE THREAD

**Issue by Fangkainakecong** [huajiqaq/Hydrogen#50]
您好，我用氢知乎最新版遇到bug反馈一下。手机连接wifi的时候，热榜不加载，账号不登录，大部分回答打不开，像断网一样，但是搜索能搜出来。断开wifi一切恢复正常。wifi是没有任何问题的，测速很快，用其他软件和看视频也没问题.
![Screenshot_2024-06-05-03-52-07-902_com.zhihu.hydrogen.x.jpg](https://github.com/huajiqaq/Hydrogen/assets/151126591/67514503-6a57-4e24-92cf-3196405c47e7)

![Screenshot_2024-06-05-03-51-56-688_com.zhihu.hydrogen.x.jpg](https://github.com/huajiqaq/Hydrogen/assets/151126591/4364f51e-174e-44f5-9af3-8980ac210eb7)

![Screenshot_2024-06-05-03-51-37-952_com.zhihu.hydrogen.x.jpg](https://github.com/huajiqaq/Hydrogen/assets/151126591/52b4c0c7-69e1-4b2d-8471-dd5d69daf82a)

**Comment by huajiqaq** [comment]
这个不知道 估计是androlua+的原因 后续如果androlua+升级了会升级androlua+的版本 现在引用的androlua+都会内存泄露

**Comment by Fangkainakecong** [comment]
已经解决，感谢
