### ISSUE TITLE
字体错误

### ISSUE THREAD

**Issue by 79279emtion** [huajiqaq/Hydrogen#52]
美国人煌大唠遏耘是社型碎惜偎，这壹于叨稿豪美醒人链的组织筏何鸵买性，挺搅卦砚合绳，店革窍相牍制。呼脖泳和世命贵俺来锻列锐石肛乏制度兑坦害鸣，桶该窃告芭洗消养幻梳的乌立，鸣加在矿性仇祸，如泛旅来，政颖当茫笑巡淤。这是正文的错误内容

美国人最大的问题是社会碎片化，这等于破坏了美国人民的组织性何团结性，无法形成合力，反而互相牵制。红脖子和黑命贵本来都是美国政治制度的受害者，应该团结起来争取自已的利益，可现在互相仇视，如此一来，政府当然笑开花。这是正确的表示。

**Comment by shizhx** [comment]
同发现关注 Tab 页列表乱码，点进去正文是好的

**Comment by huajiqaq** [comment]
乱码是因为知乎检测到该账号存在恶意使用 至于软件无法解除

**Comment by puzzle9** [comment]
> 乱码是因为知乎检测到该账号存在恶意使用 至于软件无法解除

有没有具体的检测条件啥的 目前过会好像就正常了

**Comment by huajiqaq** [comment]
还有一种 退出登录后重新登录即可
这主要归结于知乎的反爬机制 如果频繁出现推荐使用官方客户端
