### ISSUE TITLE
无法手机号码登录

### ISSUE THREAD

**Issue by cheerandclaps** [huajiqaq/Hydrogen#56]
似乎应该出captcha但没有，报错信息如图，密码登录好像知乎本身也被禁用。
测试手机浏览器登录没问题，MIUI13，安卓12
![hydrogen](https://github.com/huajiqaq/Hydrogen/assets/30248980/b88222ef-0a1d-49ea-9d55-dafc7a8f6942)

**Comment by 137943103** [comment]
我这边也是同样问题，更换旧版也不行

**Comment by huajiqaq** [comment]
因为当时调试内置了账号cookie导致 现已删除
