### ISSUE TITLE
目前版本的Hydrogen貌似无法登陆，显示“ERR_TRICKET_NOT_EXIST”请问有解决方法嘛。

### ISSUE THREAD

**Issue by sdkskld** [huajiqaq/Hydrogen#58]

**Comment by sdkskld** [comment]
![Screenshot_20240616_180609.jpg](https://github.com/huajiqaq/Hydrogen/assets/162863702/f1af5778-c605-4465-855c-bbe2ca530585)

**Comment by sdkskld** [comment]
设备是vivo y9s，Android9

**Comment by Alpha-Qian** [comment]
+1
![Uploading IMG_20240616_215803.jpg…]()

**Comment by Alpha-Qian** [comment]
+1
![Uploading IMG_20240616_215803.jpg…]()

**Comment by Alpha-Qian** [comment]
安卓13也不行
![Uploading IMG_20240616_215803.jpg…]()

**Comment by BH2WFR** [comment]
我也有这个问题

**Comment by XIAOCHEN-NYE** [comment]
俺也一样

**Comment by huajiqaq** [comment]
因为当时调试内置了账号cookie导致 现已删除
