### ISSUE TITLE
0.519版上下滑动时极易不小心左右切换回答

### ISSUE THREAD

**Issue by wangnick2017** [huajiqaq/Hydrogen#60]
如题，在上下滑动回答内容的时候，滑动路径稍有偏向就左右切换回答了

**Comment by wangnick2017** [comment]
补充：实测发现这个问题出现在新打开一篇长回答刚刚开始往下翻的时候，到了某个点就突然不能上下翻动只能左右滑动，这样就会很容易不小心切换回答，见下方录屏

https://github.com/huajiqaq/Hydrogen/assets/33253388/cdb55ccf-7469-48b0-9aa2-7d9a7cc07680

**Comment by huajiqaq** [comment]
考虑使用反射解决这个问题 现在正在测试兼容性

**Comment by polly0079** [comment]
有人提啦，那就等一个更新，先用回上一版～～

**Comment by wangnick2017** [comment]
可能是我太强迫症了（作者如果觉得不重要可以选择无视的），刚刚更新的0.52版这个问题改善了很多，但还是会出现滑动不畅的场景，下面这个视频就是一例

https://github.com/huajiqaq/Hydrogen/assets/33253388/d8ca6793-0094-4d6e-94b8-e30d63ab8c05

**Comment by huajiqaq** [comment]
在最新版本已尝试修复

**Comment by huajiqaq** [comment]
在最新版再次尝试优化

**Comment by wangnick2017** [comment]
用了一天，现在这个效果堪称完美！
大佬辛苦啦
