### ISSUE TITLE
6月22更新之后看不了了，而且之前版本也是列表字体大小不一，字体大小还会变动，一会大一会小，我是小米澎湃系统

### ISSUE THREAD

**Issue by Fangkainakecong** [huajiqaq/Hydrogen#62]
6月22更新后就所有回答点开就是下面这样子
![Screenshot_2024-06-23-08-07-33-067_com.zhihu.hydrogen.x.jpg](https://github.com/huajiqaq/Hydrogen/assets/151126591/2319e964-45cb-47a6-8af8-0807783c9e6d)

**Comment by plwd2022** [comment]
我也看不了了，更新完之后以为是数据不兼容，清除完数据打开也不行。
Runtime error: Attempt to invoke virtual method 'java.lang.reflect.Constructor[] java.lang.Class.getConstructors()' on a null object reference
stack traceback:
	[C]: in function 'luajava.override'
	...a/user/0/com.zhihu.hydrogen.x/files/sub/Welcome/main.lua:52: in function 'MyPageView'
	/data/user/0/com.zhihu.hydrogen.x/app_lua/loadlayout2.lua:506: in function 'loadlayout2'
	/data/user/0/com.zhihu.hydrogen.x/app_lua/loadlayout2.lua:540: in function 'loadlayout2'
	/data/user/0/com.zhihu.hydrogen.x/app_lua/loadlayout2.lua:540: in function 'loadlayout2'
	/data/user/0/com.zhihu.hydrogen.x/app_lua/loadlayout2.lua:540: in function 'loadlayout2'
	...a/user/0/com.zhihu.hydrogen.x/files/sub/Welcome/main.lua:76: in main chunk

**Comment by polly0079** [comment]
哈哈同样的问题…心疼一下作者

**Comment by plwd2022** [comment]
点开官方的历史版本链接下旧的用
workdrive.zohopublic.com.cn/folder/8ix3he340c5c34eb540be9db366077c3fde26?layout=list
