### ISSUE TITLE
会在根目录创建AndroLua空文件夹

### ISSUE THREAD

**Issue by life4rent119** [huajiqaq/Hydrogen#69]
软件版本 5208
系统 oneui4.1

05、06、07、08几个版本都会被Google检测为有害应用

**Comment by huajiqaq** [comment]
使用google play扫描扫描结果是安全 如果真的也是误报 因为前几年有人使用androlua+制作了送给最好的他 导致被误报

**Comment by huajiqaq** [comment]
类似于iapp的误报一样

**Comment by huajiqaq** [comment]
至于创建androlua文件夹 这是所有androlua+软件的默认形式 当有错误日志会生成在该目录下
