### ISSUE TITLE
切换回答过于灵敏

### ISSUE THREAD

**Issue by xhh-an** [huajiqaq/Hydrogen#70]
不同回答切换似乎有些太过灵敏，本来想想下划回答非常容易切到上一个/下一个回答。找了一下似乎没有找到设置灵敏度or是否开心左右划功能。或者难道是自己手机原因吗:荣耀magicv2

**Comment by wangnick2017** [comment]
在设置里打开“回答单页模式”就能关闭左右切换回答功能

**Comment by xhh-an** [comment]
> 在设置里打开“回答单页模式”就能关闭左右切换回答功能

未看到相关设置？

**Comment by xhh-an** [comment]
> 在设置里打开“回答单页模式”就能关闭左右切换回答功能

本来没找到，更新了之后就有了，谢谢解答

**Comment by xhh-an** [comment]
> 在设置里打开“回答单页模式”就能关闭左右切换回答功能

bytheway，最新版本的灵敏度已经非常适合～不需要关闭了，谢谢～(才更新)
