### ISSUE TITLE
让应用图标的背景始终为蓝色

### ISSUE THREAD

**Issue by xuangeyouneihan** [huajiqaq/Hydrogen#71]
MIUI和澎湃OS上在深色模式时点开应用或重启系统桌面会将应用图标的背景变成白色，实在是比较丑

![IMG_20240718_134700](https://github.com/user-attachments/assets/bb9e9bae-5443-4969-b72e-80f991deea59)

**Comment by huajiqaq** [comment]
当关闭深色模式重启app 软件的颜色会回到原颜色

**Comment by huajiqaq** [comment]
这个不是代码能控制的 必须要修改xml文件为全体的 所以不准备修复
