### ISSUE TITLE
音量键切换回答不起作用

### ISSUE THREAD

**Issue by Diaojinping** [huajiqaq/Hydrogen#73]
应该最近几个版本都有这个问题，在设置页面选择音量键切换回答后不起作用，再返回设置页面后发现仍为未勾选状态。重启也没用

**Comment by Diaojinping** [comment]
牛啊，这么快就修复了！

**Comment by huajiqaq** [comment]
可能更新的时候多删了一行代码导致的 实际上这并不需要多长时间修复
