### ISSUE TITLE
请问为什么hydrogen上的问答中的回答与原版知乎问答上的回答的默认排序不一样

### ISSUE THREAD

**Issue by Undertaker4053** [huajiqaq/Hydrogen#85]
如图
![Screenshot_20240805_203333_com.zhihu.android.jpg](https://github.com/user-attachments/assets/e7e84061-85e3-4d81-9e1b-821981e0d59a)

![Screenshot_20240805_203306_com.zhihu.hydrogen.x.jpg](https://github.com/user-attachments/assets/b9ac0979-1a62-4953-8430-dabc435712fa)

**Comment by huajiqaq** [comment]
或许是和软件的api不一致？这个会研究研究的

**Comment by Undertaker4053** [comment]
感谢🙏作者大大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月6日(周二) 上午6:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huajiqaq/Hydrogen] 请问为什么hydrogen上的问答中的回答与原版知乎问答上的回答的默认排序不一样 (Issue #85)




 
或许是和软件的api不一致？这个会研究研究的
