### ISSUE TITLE
全站下面的内容总是出现很多重复。

### ISSUE THREAD

**Issue by waterfallsky** [huajiqaq/Hydrogen#88]
全站下面内容有很多重复，一直升级到最新版，一直有这个问题
![IMG_20240806_182239](https://github.com/user-attachments/assets/d35811bc-53a4-4104-a325-3caba7bd1f06)

**Comment by huajiqaq** [comment]
无法解决 在之前就尝试解决 你可尝试使用官方软件解决这个问题
