### ISSUE TITLE
增加隐藏热榜图片的设置

### ISSUE THREAD

**Issue by amokiel** [huajiqaq/Hydrogen#9]
目前热榜显示图片的效果不太好，可以考虑增加一个隐藏热榜图片的设置。这样就可以和首页，关注列表保持一致，更协调美观一些。个人更倾向于看一下评论和专栏里面的图片，热榜似乎不显示图片更好一些。开发者辛苦了，app好看好用，由衷感谢！

**Comment by huajiqaq** [comment]
最
