### ISSUE TITLE
切换webview报错

### ISSUE THREAD

**Issue by Lucas04-nhr** [huajiqaq/Hydrogen#90]
![Screenshot_20240811_234014.jpg](https://github.com/user-attachments/assets/24073f5a-3566-4d7d-b279-cc7e70873642)

本机系统信息
OriginOS 4(Android 14)
内核版本5.10.198

Android System Webview 版本128.0.6613.25 (661302542)

Google Chrome版本
127.0.6533.103 (653310333)

**Comment by Lucas04-nhr** [comment]
![Screenshot_2024_0811_234720.png](https://github.com/user-attachments/assets/901a0c6b-2ddd-4c3b-bb82-0ac5969f7768)

![Screenshot_2024_0811_234738.png](https://github.com/user-attachments/assets/750c0db7-5482-4ef2-bbd6-f6bb16384a08)

**Comment by huajiqaq** [comment]
这只是针对于较低webview版本所提供的功能 你不需要开启这个功能
