### ISSUE TITLE
[Bug]启动App时首页不会自动刷新/加载

### ISSUE THREAD

**Issue by Lucas04-nhr** [huajiqaq/Hydrogen#99]
如题，最新版本（535）在打开App时不会自动加载首页内容，显示为白屏，必须向上/向下滑动或是切换页签才能加载出内容
![Screenshot_20240826_090934.jpg](https://github.com/user-attachments/assets/026b5911-7626-42ac-9a39-5c8e9f916b45)

**Comment by NoLaunch** [comment]
问题同上
![Screenshot_20240826-110439.png](https://github.com/user-attachments/assets/f097a8e9-f765-4120-84c4-8e046ca43ae0)

**Comment by Lucas04-nhr** [comment]
参见7fb76f1
